"""The website must not carry hand-typed statistics.

Twice now a rebuild has moved a published number while the page kept showing the
old one: the domain-randomization table went on claiming a +36% held-out return
after the artifact said +47%, and the market explorer was still quoting a +275%
run and ``p = 0.97`` months after both had been superseded. Neither was caught by
a test, because nothing tested the *page* against the *experiments*.

That is the project's own thesis turned on itself. A number that has drifted away
from the run that produced it is not a rounding problem, it is a false claim, and
the site argues at length that those should be findable mechanically.

So these tests pin the mechanism rather than the digits: results reach the page
from generated artifacts, and the few literal figures that remain are superseded
runs that say so and cite the commit they came from.
"""

from __future__ import annotations

import json
import os
import re

import pytest

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(REPO, "docs")


def _read(*parts: str) -> str:
    with open(os.path.join(DOCS, *parts), encoding="utf-8") as fh:
        return fh.read()


@pytest.fixture(scope="module")
def index() -> str:
    return _read("index.html")


@pytest.fixture(scope="module")
def app_js() -> str:
    return _read("app.js")


# --------------------------------------------------------------------------- #
# The shim and the artifact are the same numbers                               #
# --------------------------------------------------------------------------- #
def test_the_ablation_shim_matches_the_artifact_it_was_generated_from():
    """docs/ablation.js is written by the sweep; it must not be edited apart."""
    shim = _read("ablation.js")
    assert shim.startswith("/* Auto-generated by tools/ablation_multiseed.py")

    payload = json.loads(shim[shim.index("=") + 1: shim.rindex(";")])
    with open(os.path.join(DOCS, "assets", "ablation_multiseed.json"),
              encoding="utf-8") as fh:
        artifact = json.load(fh)
    assert payload["summary"] == artifact["summary"]
    assert payload["per_seed"] == artifact["per_seed"]


def test_the_shim_carries_the_per_seed_values_not_just_the_means():
    """A mean alone cannot be re-checked; the seeds behind it can."""
    shim = _read("ablation.js")
    payload = json.loads(shim[shim.index("=") + 1: shim.rindex(";")])
    for market in ("stock", "crypto"):
        for arm in ("single", "domain"):
            block = payload["summary"]["markets"][market][arm]
            assert len(block["oos_per_seed"]) == len(payload["summary"]["seeds"])
            assert len(block["in_per_seed"]) == len(payload["summary"]["seeds"])


# --------------------------------------------------------------------------- #
# The page renders results, it does not restate them                           #
# --------------------------------------------------------------------------- #
def test_the_ablation_table_is_a_render_target_not_typed_rows(index: str):
    assert '<tbody id="abl-body"></tbody>' in index
    # the four rows that used to be typed here
    assert "Stocks &middot; single asset" not in index
    assert "Crypto &middot; across tickers" not in index


def test_the_explorer_verdict_is_computed_from_the_significance_artifact(app_js: str):
    assert "const VERDICT = {" not in app_js, "the hard-coded verdict strings are back"
    assert "function verdictFor(market)" in app_js
    assert "window.RL_SIGNIFICANCE" in app_js


def test_the_result_section_reads_the_ablation_global(app_js: str):
    assert "window.RL_ABLATION" in app_js
    assert "function renderResult(" in app_js


def test_the_page_loads_every_generated_data_file(index: str):
    for shim in ("results.js", "significance.js", "learning.js", "ablation.js"):
        assert f'<script src="{shim}"></script>' in index, shim


# --------------------------------------------------------------------------- #
# What literal figures remain must be superseded runs that say so              #
# --------------------------------------------------------------------------- #

# A percentage with a sign reads as a result. Bare percentages are used for
# widths, opacities and prose ("100% of the time"), so signed literals are the
# ones worth policing.
_SIGNED_PCT = re.compile(r"(?:\+|&minus;|−|-)\d[\d,]*(?:\.\d+)?%")

# Each exemption needs a reason, and the reason has to be checkable on the page.
_ALLOWED = {
    "+0.0%": "hero chart placeholder, overwritten by initHero() on load",
    "+10%": "default position of the power-calculator effect-size slider",
    "+275.45%": "superseded v1 run, labelled and cited to commit d4c0ef9",
    "+19.57%": "superseded v1 benchmark, cited alongside it",
}


def test_every_literal_percentage_on_the_page_is_accounted_for(index: str):
    found = set(_SIGNED_PCT.findall(index))
    unexplained = found - set(_ALLOWED)
    assert not unexplained, (
        "literal result figures appeared in index.html: "
        f"{sorted(unexplained)}. Render them from a generated artifact, or add "
        "them to _ALLOWED with a reason if they are genuinely not live results."
    )


def test_the_superseded_figures_are_labelled_as_superseded(index: str):
    """Quoting an old run is fine. Quoting it as if current is not."""
    i = index.index("+275.45%")
    context = index[i: i + 1400]
    assert "Superseded" in context
    assert "d4c0ef9" in context, "the superseded run must cite the commit it came from"
    assert "+19.57%" in context, "the old benchmark belongs next to the old return"


def test_the_reproducibility_section_states_its_own_limit(index: str):
    """A pinned-window claim that omits the window is marketing."""
    assert 'id="repro-warn"' in index
    app = _read("app.js")
    i = app.index("repro-warn")
    context = app[i: i + 700]
    assert "later snapshot" in context
    assert "DATA.generated" in context


# --------------------------------------------------------------------------- #
# Source links must point at files that exist                                  #
# --------------------------------------------------------------------------- #
_REPO_LINK = re.compile(
    r"github\.com/Danny-397/RL-for-Crypto-and-stocks-/(?:blob|tree)/"
    r"(?:main|[0-9a-f]{7,40})/([^\"#]+)"
)


def test_every_link_into_the_repository_resolves(index: str):
    """A "view source" link that 404s is worse than no link.

    Two of these were written from memory rather than looked up
    (``rl_trader/agents/ppo_agent.py``, ``rl_trader/data/preprocessor.py``) and
    neither path has ever existed in this repository.
    """
    linked = sorted(set(_REPO_LINK.findall(index)))
    assert linked, "the contextual source links have gone missing"
    missing = [p for p in linked if not os.path.exists(os.path.join(REPO, p))]
    assert not missing, f"index.html links to paths that do not exist: {missing}"


def test_the_claims_beside_the_links_match_the_code_they_point_at():
    """The 'splits' claim names a file; that file must actually fit on train."""
    index = _read("index.html")
    i = index.index("Chronological, with scalers fit on the training")
    context = index[i: i + 300]
    match = _REPO_LINK.search(context)
    assert match, "the splits claim lost its source link"
    with open(os.path.join(REPO, match.group(1)), encoding="utf-8") as fh:
        source = fh.read()
    assert "scaler" in source and "train_end" in source


# --------------------------------------------------------------------------- #
# Other countable claims on the page                                           #
# --------------------------------------------------------------------------- #
def test_the_test_count_in_the_stats_strip_is_plausible(index: str):
    """The strip claimed 290 while the suite stood at 346 -- stale in the same
    way the ablation table was.

    Bounded rather than pinned. Collecting the real total from inside a test run
    is unreliable when only part of the suite is selected, so this compares the
    claim against the number of ``def test_`` definitions: the collected total is
    always at least that (parametrize only expands it), and a claim far above it
    is an overstatement. Either bound failing means the number needs a look.
    """
    match = re.search(
        r'data-count="(\d+)">\d+</div><div class="lbl">Tests passing', index)
    assert match, "the tests-passing stat has gone missing"
    claimed = int(match.group(1))

    defined = 0
    tests_dir = os.path.join(REPO, "tests")
    for name in os.listdir(tests_dir):
        if not name.endswith(".py"):
            continue
        with open(os.path.join(tests_dir, name), encoding="utf-8") as fh:
            defined += len(re.findall(r"^\s*def test_", fh.read(), re.M))

    assert claimed >= defined, (
        f"the page claims {claimed} tests but {defined} are defined -- the strip "
        "is stale, update it")
    assert claimed <= defined * 2, (
        f"the page claims {claimed} tests against {defined} definitions, which "
        "parametrize is unlikely to explain")


def test_the_live_widget_is_framed_as_research_not_as_a_trading_tool(index: str):
    """It runs a frozen policy on unseen tickers; the copy has to say so."""
    i = index.index('id="live"')
    block = index[i: i + 3000]
    assert "Out-of-distribution test" in block
    assert "never trained on" in block
    assert "not financial advice" in block
    assert "no retraining" in block
